// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpoMusic.Api.Data;

#nullable disable

namespace SpoMusic.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpoMusic.Api.Entities.ListeningHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("playedAt");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trackId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TrackId", "PlayedAt")
                        .IsUnique();

                    b.ToTable("ListeningHistory", (string)null);
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("CommonArtists")
                        .HasColumnType("integer")
                        .HasColumnName("commonArtists");

                    b.Property<int>("CommonTracks")
                        .HasColumnType("integer")
                        .HasColumnName("commonTracks");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<double>("MatchScore")
                        .HasColumnType("double precision")
                        .HasColumnName("matchScore");

                    b.Property<string>("User1Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user1Id");

                    b.Property<string>("User2Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user2Id");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.SpotifyToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accessToken");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresAt");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("integer")
                        .HasColumnName("expiresIn");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refreshToken");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SpotifyToken", (string)null);
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.Track", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("album");

                    b.PrimitiveCollection<List<string>>("Artists")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("artists");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("durationMs");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("previewUrl");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotifyId");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyId")
                        .IsUnique();

                    b.ToTable("Track", (string)null);
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("text")
                        .HasColumnName("spotifyId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SpotifyId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.UserTopTrack", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trackId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TrackId")
                        .IsUnique();

                    b.ToTable("UserTopTrack", (string)null);
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.ListeningHistory", b =>
                {
                    b.HasOne("SpoMusic.Api.Entities.Track", "Track")
                        .WithMany("ListeningHistories")
                        .HasForeignKey("TrackId")
                        .HasPrincipalKey("SpotifyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpoMusic.Api.Entities.User", "User")
                        .WithMany("ListeningHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.Match", b =>
                {
                    b.HasOne("SpoMusic.Api.Entities.User", "User1")
                        .WithMany("MatchesInitiated")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpoMusic.Api.Entities.User", "User2")
                        .WithMany("MatchesReceived")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.SpotifyToken", b =>
                {
                    b.HasOne("SpoMusic.Api.Entities.User", "User")
                        .WithOne("SpotifyToken")
                        .HasForeignKey("SpoMusic.Api.Entities.SpotifyToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.UserTopTrack", b =>
                {
                    b.HasOne("SpoMusic.Api.Entities.Track", "Track")
                        .WithMany("UserTopTracks")
                        .HasForeignKey("TrackId")
                        .HasPrincipalKey("SpotifyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpoMusic.Api.Entities.User", "User")
                        .WithMany("TopTracks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.Track", b =>
                {
                    b.Navigation("ListeningHistories");

                    b.Navigation("UserTopTracks");
                });

            modelBuilder.Entity("SpoMusic.Api.Entities.User", b =>
                {
                    b.Navigation("ListeningHistories");

                    b.Navigation("MatchesInitiated");

                    b.Navigation("MatchesReceived");

                    b.Navigation("SpotifyToken");

                    b.Navigation("TopTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
